services:
  localstack:
    container_name: "localaws"
    image: localstack/localstack-pro
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - LOCALSTACK_AUTH_TOKEN=ls-quXatEGa-2462-Hate-3512-SAtEqitUea51
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net-localstack

  # mail:
  #   container_name: "mail"
  #   image: bytemark/smtp
  #   networks:
  #     - net-localstack
  #   restart: always
  # server:
  #   build:
  #     context: .
  #     dockerfile: nginx.Dockerfile
  #   container_name: ngnix_server
  #   ports:
  #     - "9000:8080"
  #   networks:
  #     - net-localstack

networks:
  net-localstack:
    external: true
